INSERT INTO stage.inform_task
(
    tm_task_id,
    tm_task_type_cd,
    episode_type_cd,
    tm_status_cd,
    mpioip,
    ds_cd,
    end_dt,
    mo_cd,
    planned_start_dt,
    planned_end_dt,
    group_cd,
    disp_type_cd,
    gender_code,
    full_age,
    smo_executor_cd,
    tfoms_cd,
    region_smo_cd,
    region_mo_cd,
    smo_user_id,
    created_dt,
    updated_dt,
    tm_closed_dt,
    creation_type,
    logical_id,
    comment,
    episode_cmp_id,
    tm_event_type,
    profile_cd
)
SELECT
    id AS tm_task_id,
    coalesce(task_type_cd, '') AS tm_task_type_cd,
    coalesce(episode_type_cd, '') AS episode_type_cd,
    coalesce(status_cd, '') AS tm_status_cd,
    mpi_oip AS mpioip,
    coalesce(diagnosis_cd, '') AS ds_cd,
    coalesce(end_date, toDate('1970-01-01')) AS end_dt,
    coalesce(mo_cd, '') AS mo_cd,
    planned_start_date AS planned_start_dt,
    planned_end_date AS planned_end_dt,
    toInt32OrZero(diagnosis_group_cd) AS group_cd,
    disp_type_cd AS disp_type_cd,
    coalesce(gender_cd, '') AS gender_code,
    coalesce(full_age, 0) AS full_age,
    coalesce(smo_cd, '') AS smo_executor_cd,
    coalesce(tfoms_cd, '') AS tfoms_cd,
    substring(coalesce(smo_cd, ''), 1, 2) AS region_smo_cd,
    substring(coalesce(mo_cd, ''), 1, 2) AS region_mo_cd,
    coalesce(smo_user_id, '') AS smo_user_id,
    coalesce(created_at, _loaded_at) AS created_dt,
    coalesce(updated_at, created_at, _loaded_at) AS updated_dt,
    close_date AS tm_closed_dt,
    creation_type AS creation_type,
    logical_id AS logical_id,
    comment AS comment,
    toInt64OrNull(episode_cmp_id) AS episode_cmp_id,
    operation_type AS tm_event_type,
    toInt32OrZero(medical_profile_cd) AS profile_cd
FROM raw.dn_inform_task;
