CREATE TABLE IF NOT EXISTS tmp.done_task_month_source
(
    task_id UUID,
    task_status_cd Int32,
    closed_dt Date,
    closed_y Int32,
    closed_q Int32,
    closed_m Int32,
    region_smo_cd String,
    profile_cd String,
    dn_group_cd String,
    smo_cd String,
    mo_cd String
)
ENGINE = MergeTree
ORDER BY (closed_y, closed_q, closed_m, task_status_cd, region_smo_cd, profile_cd, dn_group_cd, smo_cd, mo_cd, task_id);

CREATE TABLE IF NOT EXISTS cube.done
(
    f_region_smo_cd String,
    f_profile_cd String,
    f_dn_group_cd String,
    f_y Int32,
    f_q Int32,
    f_smo String,
    f_mo String,
    p_done_m1_v UInt64,
    p_assumpt_m1_v UInt64,
    c_done_m1_v UInt64,
    c_assumpt_m1_v UInt64,
    p_done_m2_v UInt64,
    p_assumpt_m2_v UInt64,
    c_done_m2_v UInt64,
    c_assumpt_m2_v UInt64,
    p_done_m3_v UInt64,
    p_assumpt_m3_v UInt64,
    c_done_m3_v UInt64,
    c_assumpt_m3_v UInt64,
    p_done_m4_v UInt64,
    p_assumpt_m4_v UInt64,
    c_done_m4_v UInt64,
    c_assumpt_m4_v UInt64,
    p_done_m5_v UInt64,
    p_assumpt_m5_v UInt64,
    c_done_m5_v UInt64,
    c_assumpt_m5_v UInt64,
    p_done_m6_v UInt64,
    p_assumpt_m6_v UInt64,
    c_done_m6_v UInt64,
    c_assumpt_m6_v UInt64,
    p_done_m7_v UInt64,
    p_assumpt_m7_v UInt64,
    c_done_m7_v UInt64,
    c_assumpt_m7_v UInt64,
    p_done_m8_v UInt64,
    p_assumpt_m8_v UInt64,
    c_done_m8_v UInt64,
    c_assumpt_m8_v UInt64,
    p_done_m9_v UInt64,
    p_assumpt_m9_v UInt64,
    c_done_m9_v UInt64,
    c_assumpt_m9_v UInt64,
    p_done_m10_v UInt64,
    p_assumpt_m10_v UInt64,
    c_done_m10_v UInt64,
    c_assumpt_m10_v UInt64,
    p_done_m11_v UInt64,
    p_assumpt_m11_v UInt64,
    c_done_m11_v UInt64,
    c_assumpt_m11_v UInt64,
    p_done_m12_v UInt64,
    p_assumpt_m12_v UInt64,
    c_done_m12_v UInt64,
    c_assumpt_m12_v UInt64,
    insert_dttm DateTime64(3, 'Europe/Moscow'),
    update_dttm DateTime64(3, 'Europe/Moscow')
)
ENGINE = MergeTree
ORDER BY (f_y, f_q, f_region_smo_cd, f_profile_cd, f_dn_group_cd, f_smo, f_mo);
